#!/usr/bin/env python

import os, sys, re

if __name__ == "__main__":
    text = " ".join([line.strip() for line in sys.stdin])
    prog = [line + ";" for line in text.split(";") if len(line) > 0]

    file_id = 0
    current_file = []
    for statement in prog:
        current_file.append(statement)
        if re.search("QUERY .+;", statement):
            fout = open(str(file_id) + ".stp", "w")
            for line in current_file:
                print >> fout, line
            fout.close()
            current_file = []
            file_id += 1
