#!/bin/bash

$APPS_DIR/aget/setup $*
# If the common setup fails, we fail. 
if [ $? -ne 0 ]; then
	exit 1
fi

patch -p1 < structurize.patch
cd aget-$1
patch -p1 < ../fix-pwrite.patch
patch -p1 < ../fake-pwrite.patch
cd ..
