#!/usr/bin/env python

import os, sys

if __name__ == "__main__":
    action = ""
    if len(sys.argv) >= 2:
        action = sys.argv[1]

    os.chdir("parsec-2.1")
    if action == "clean":
        os.system("bin/parsecmgmt -a fullclean -c llvm -p blackscholes")
        os.system("bin/parsecmgmt -a fullclean -c llvm -p swaptions")
        os.system("bin/parsecmgmt -a fullclean -c llvm -p streamcluster")
        os.system("bin/parsecmgmt -a fullclean -c llvm -p canneal")
        os.system("bin/parsecmgmt -a fullclean -c llvm -p fluidanimate")
        # os.system("bin/parsecmgmt -a fullclean -c llvm -p dedup")
        os.system("bin/parsecmgmt -a fullclean -c llvm -p ferret")
        # os.system("bin/parsecmgmt -a fullclean -c llvm -p facesim")
    elif action == "uninstall":
        os.system("bin/parsecmgmt -a fulluninstall -c llvm -p blackscholes")
        os.system("bin/parsecmgmt -a fulluninstall -c llvm -p swaptions")
        os.system("bin/parsecmgmt -a fulluninstall -c llvm -p streamcluster")
        os.system("bin/parsecmgmt -a fulluninstall -c llvm -p canneal")
        os.system("bin/parsecmgmt -a fulluninstall -c llvm -p fluidanimate")
        # os.system("bin/parsecmgmt -a fulluninstall -c llvm -p dedup")
        os.system("bin/parsecmgmt -a fulluninstall -c llvm -p ferret")
        # os.system("bin/parsecmgmt -a fulluninstall -c llvm -p facesim")
    else:
        os.system("bin/parsecmgmt -a build -c llvm -p blackscholes")
        os.system("bin/parsecmgmt -a build -c llvm -p swaptions")
        os.system("bin/parsecmgmt -a build -c llvm -p streamcluster")
        os.system("bin/parsecmgmt -a build -c llvm -p canneal")
        os.system("bin/parsecmgmt -a build -c llvm -p fluidanimate")
        # os.system("bin/parsecmgmt -a build -c llvm -p dedup")
        os.system("bin/parsecmgmt -a build -c llvm -p ferret")
        # os.system("PHYSBAM=`pwd`/pkgs/apps/facesim/obj/amd64-linux.llvm bin/parsecmgmt -a build -c llvm -p facesim")
