#!/usr/bin/env python

# TODO: Move to $APPS_DIR

import os

if __name__ == "__main__":
    os.system("$APPS_DIR/parsec/setup")
    os.chdir("parsec-2.1")
    os.system("patch -p1 < ../support-llvm.patch")
    os.system("patch -p1 < ../disable-parsec-barrier.patch")
    os.system("patch -p1 < ../fix-swaptions.patch")
    os.system("patch -p1 < ../fix-blackscholes.patch")
    os.system("patch -p1 < ../fix-streamcluster.patch")
    os.system("patch -p1 < ../fix-ferret.patch")
