#!/bin/bash

function print_usage
{
	echo "print <insts | bbs | funcs> <.bc>"
}

if [ "$1" = "" ] || [ "$2" = "" ]; then
	print_usage
	exit 1
fi

opt -load $LLVM_ROOT/install/lib/libidm.so -idm --print-$1 -analyze < $2

