#!/bin/bash

if [ "$1" = "" -o "$1" = "-h" -o "$1" = "--help" ]; then
	echo "Usage: $0 <program name> [extra options to the instrumentor]  [extra link flags, e.g. -lbz2]"
	exit 1
fi

if [ -z $SLICER_ROOT ]; then
	echo "SLICER_ROOT is not set"
	exit 1
fi

opt -o $1.bc1 \
	-load $LLVM_ROOT/install/lib/id-manager.so \
	-load $LLVM_ROOT/install/lib/bc2bdd.so \
	-load $LLVM_ROOT/install/lib/callgraph-fp.so \
	-load $LLVM_ROOT/install/lib/mbb.so \
	-load $LLVM_ROOT/install/lib/cfg.so \
	-load $LLVM_ROOT/install/lib/slicer-trace.so \
	$2 \
	-instrument-each-bb \
	-instrument \
	< $1.id.bc
if [ $? != 0 ]; then
	exit $?
fi

llvm-ld $1.bc1 $SLICER_ROOT/lib/trace/tracing.bc -b $1.trace.bc \
	-link-as-library -disable-opt
if [ $? != 0 ]; then
	exit $?
fi

llc $1.trace.bc -o $1.trace.s -O0
if [ $? != 0 ]; then
	exit $?
fi

g++ $1.trace.s -o $1.trace -pthread $3
if [ $? != 0 ]; then
	exit $?
fi
