#!/bin/bash

if [ "$1" = "" -o "$2" = "" ]; then
	echo "Usage: $0 <input: full trace> <output: landmark trace> [extra options passed to the landmark-trace-builder]"
	echo "full trace: .ft"
	echo "landmark trace: .lt"
	exit 1
fi

opt -stats -disable-output \
	-load $LLVM_ROOT/install/lib/id-manager.so \
	-load $LLVM_ROOT/install/lib/bc2bdd.so \
	-load $LLVM_ROOT/install/lib/callgraph-fp.so \
	-load $LLVM_ROOT/install/lib/mbb.so \
	-load $LLVM_ROOT/install/lib/cfg.so \
	-load $LLVM_ROOT/install/lib/slicer-trace.so \
	-build-landmark-trace \
	-fulltrace $1 \
	-output-landmark-trace $2 \
	${@:3} \
	< `echo $1| sed 's/\.ft$/.id.bc/g'`
