#!/bin/bash

# Author: Jingyue

if [ "$1" = "" -o "$2" = "" ]; then
	echo "Usage: $0 <input: id.bc> <output: slice.bc> [extra flags passed to the max-slicer]"
	exit 1
fi

opt -stats -o $2 \
	-load $LLVM_ROOT/install/lib/id-manager.so \
	-load $LLVM_ROOT/install/lib/bc2bdd.so \
	-load $LLVM_ROOT/install/lib/callgraph-fp.so \
	-load $LLVM_ROOT/install/lib/mbb.so \
	-load $LLVM_ROOT/install/lib/cfg.so \
	-load $LLVM_ROOT/install/lib/slicer-trace.so \
	-load $LLVM_ROOT/install/lib/max-slicing.so \
	-max-slicing \
	${@:3} \
	-input-landmark-trace `echo $1| sed 's/\.id.bc$/.lt/g'` \
	< $1
