#!/bin/bash

if [ -z $1 ] || [ -z $2 ]; then
	echo "Usage: $0 <input: .bc> <output: .prep.bc> [extra options forwarded to the preparer]"
	exit 1
fi

opt -o $2 \
	-load $LLVM_ROOT/install/lib/libid-manager.so \
	-load $LLVM_ROOT/install/lib/libbc2bdd.so \
	-load $LLVM_ROOT/install/lib/libcallgraph-fp.so \
	-load $LLVM_ROOT/install/lib/libmbb.so \
	-load $LLVM_ROOT/install/lib/libcfg.so \
	-load $LLVM_ROOT/install/lib/libpreparer.so \
	-prepare \
	${@:3} \
	< $1
