#!/bin/bash

if [ -z $1 ] || [ -z $2 ]; then
	echo "Usage: $0 <input: .bc> <output: .prep.bc> [extra options forwarded to the preparer]"
	exit 1
fi

opt -o $2 \
	-load $LLVM_ROOT/install/lib/id-manager.so \
	-load $LLVM_ROOT/install/lib/bc2bdd.so \
	-load $LLVM_ROOT/install/lib/callgraph-fp.so \
	-load $LLVM_ROOT/install/lib/mbb.so \
	-load $LLVM_ROOT/install/lib/cfg.so \
	-load $LLVM_ROOT/install/lib/preparer.so \
	-replace-mymalloc -prepare \
	${@:3} \
	< $1
