#!/bin/bash

if [ "$1" = "" -o "$2" = "" ]; then
	echo "Usage: $0 <input: .slice.bc> <output: .simple.bc> [extra options passed to the simplifier]"
	exit 1
fi

simplifier -o $2 \
	-input-landmark-trace `echo $1| sed 's/\.slice.bc$/.lt/g'` \
	${@:3} \
	< $1
