LEVEL = ../..

TOOLNAME = filter-landmark-trace

LINK_COMPONENTS = bitreader bitwriter asmparser instrumentation scalaropts ipo

CXXFLAGS += -I$(LLVM_ROOT)/install/include

include $(LEVEL)/Makefile.common
