#!/usr/bin/env python

import os, sys

if __name__ == "__main__":
    m = int(sys.argv[1])
    n = int(sys.argv[2])
    print 80 * " "
    print "%14d%14d%14d%14d%14d" %(1146, 290, 856, 0, 0)
    print "PSA%25d%14d%14d%14d" %(m, m, n, 0)
    print "%-72s" %("(1I10)           (1I10)")
    for i in range(m + 1):
        print "%10d" %(i + 1)
    for i in range(n):
        print "%10d" %(i + 1)
