#!/bin/bash

if [ "$APPS_DIR" = "" ]; then
	echo '$APPS_DIR not defined, do `export APPS_DIR=`'
	exit 1
fi

$APPS_DIR/splash2-modified/setup
cd splash2
patch -p1 < ../fix-RADIX.patch
patch -p1 < ../fix-CHOLESKY.patch
patch -p1 < ../inline-FFT.patch
cd ..
